### ISSUE TITLE
Error: cannot import name parse_table

### ISSUE THREAD

**Issue by chikalll** [picrust/picrust#264]
Hi all,

When I tried to run the "download_picrust_files.py of picrust", I got the following error:

Traceback (most recent call last):
  File "/home/qiime/miniconda3/envs/picrust/bin/download_picrust_files.py", line 26, in <module>
    from picrust.util import atomic_write
  File "/home/qiime/miniconda3/envs/picrust/lib/python2.7/site-packages/picrust/util.py", line 15, in <module>
    from biom import parse_table, Table
ImportError: cannot import name parse_table

I really have no idea where to start troubleshooting this. 

Any help is highly appreciated.

**Comment by gavinmdouglas** [comment]
Hey @chikalll,

What version of PICRUSt are you running and how was it installed? If you run `conda list` what version of biom-format are you running?


Best,

Gavin

**Comment by chikalll** [comment]
Hi Gavin

Thank you for reply.
I tried to running following version;
# Name                    Version                   Build       Channel
biom-format               2.1.7                    py27_0    bioconda
picrust                   1.1.4              pyh24bf2e0_0    bioconda

And I installed picrust by following step.
1. Install Miniconda (Python 3.6, Linux, 64-bit)
2. sh Miniconda3-latest-Linux-x86_64.sh
3. conda create -n picrust1 python=2.7.13
4.  source activate picrust1
5. conda install -c bioconda picrust

Best regards.

Chika

**Comment by chikalll** [comment]
Hi Gavin

Thank you for reply.
I tried to running following version;

Name    version    build    channel 
biom-format    2.1.7    py27_0     bioconda
picrust     1.1.4    pyh24bf2e0_0     bioconda

And I installed picrust by following step.

Install Miniconda (Python 3.6, Linux, 64-bit)
1. $sh Miniconda3-latest-Linux-x86_64.sh
2. $conda create -n picrust1 python=2.7.13
3. $source activate picrust1
4. $conda install -c bioconda picrust

Best regards.

Chika

**Comment by gavinmdouglas** [comment]
Hey @chikalll,

I can confirm that those two versions do work together so I'm not sure what the problem is exactly. Can you try re-installing in a fresh conda environment with the exact conda commands listed [here](http://picrust.github.io/picrust/install.html#install)?

**Comment by chikalll** [comment]
Hi Gavin

Thank you for reply.
I tried to run following commands. But I got error massage again....

(base) qiime@qiime-VirtualBox:~$ conda create -n picrust2 -c bioconda -c conda-forge picrust
(base) qiime@qiime-VirtualBox:~$ conda activate picrust2
(picrust2) qiime@qiime-VirtualBox:~$ download_picrust_files.py
Traceback (most recent call last):
  File "/home/qiime/miniconda3/envs/picrust2/bin/download_picrust_files.py", line 26, in <module>
    from picrust.util import atomic_write
  File "/home/qiime/miniconda3/envs/picrust2/lib/python2.7/site-packages/picrust/util.py", line 15, in <module>
    from biom import parse_table, Table
ImportError: cannot import name parse_table

Chika

**Comment by chikalll** [comment]
Hi Gavin

Thank you for reply.
I tried to run following commands. But I got error massage again....

(base) qiime@qiime-VirtualBox:$ conda create -n picrust2 -c bioconda -c conda-forge picrust
(base) qiime@qiime-VirtualBox:$ conda activate picrust2
(picrust2) qiime@qiime-VirtualBox:~$ download_picrust_files.py
Traceback (most recent call last):
File "/home/qiime/miniconda3/envs/picrust2/bin/download_picrust_files.py", line 26, in 
from picrust.util import atomic_write
File "/home/qiime/miniconda3/envs/picrust2/lib/python2.7/site-packages/picrust/util.py", line 15, in 
from biom import parse_table, Table
ImportError: cannot import name parse_table

Chika

**Comment by gavinmdouglas** [comment]
Hey again,

I see you named the conda environment `picrust2`. If you do want to use PICRUSt2 you should be looking at these install instructions instead: https://github.com/picrust/picrust2/wiki/Installation

Either way I think there must be something wrong with your conda environment. Can you try running these commands and then re-installing to see if it works?

`conda update conda`
`conda env remove -n picrust`
`conda env remove -n picrust2`
`conda clean --yes --all`

**Comment by chikalll** [comment]
Hi again,

Thank you for reply.
I tried to remove conda environment by running you recommended command and re-constructed new conda environment and re-downloaded picrust by following commands.

$ conda create -n picrust1 -c bioconda -c conda-forge picrust
$ conda activate picrust1
$ download_picrust_files.py

But I got the error again...

Traceback (most recent call last):
  File "/home/qiime/miniconda3/envs/picrust1/bin/download_picrust_files.py", line 26, in <module>
    from picrust.util import atomic_write
  File "/home/qiime/miniconda3/envs/picrust1/lib/python2.7/site-packages/picrust/util.py", line 15, in <module>
    from biom import parse_table, Table
ImportError: cannot import name parse_table

Chika

**Comment by gavinmdouglas** [comment]
Hey @chikalll,

Hmm I'm still not sure what the problem is since you can import `parse_table` from biom-format 2.1.7. Is it possible that you have conflicting library paths?

What is returned if you type:

```which biom```
```biom --version```


Thanks,

Gavin

**Comment by chikalll** [comment]
Hi gavin

Thank you for reply.
I got the following response...

(base) qiime@qiime-VirtualBox:~/Desktop$ which biom
/home/qiime/qiime_software/biom-format-1.3.1-release/bin/biom
(base) qiime@qiime-VirtualBox:~/Desktop$ biom --version
Unrecognized command --version. Please make sure that you didn't make a typo in
the command name.

To see a list of all available commands, run the following command:

   biom

(base) qiime@qiime-VirtualBox:~/Desktop$ 

Chika

**Comment by chikalll** [comment]
Hi gavin

Thank you for reply.
I got the following response...

(base) qiime@qiime-VirtualBox:/Desktop$ which biom
/home/qiime/qiime_software/biom-format-1.3.1-release/bin/biom
(base) qiime@qiime-VirtualBox:/Desktop$ biom --version
Unrecognized command --version. Please make sure that you didn't make a typo in
the command name.

To see a list of all available commands, run the following command:

biom

(base) qiime@qiime-VirtualBox:~/Desktop$

Chika

**Comment by gavinmdouglas** [comment]
You'll need to activate the `picrust1` environment before running that command since the biom version we're interested in is that environment.

**Comment by chikalll** [comment]
Hi gavin

I retried to running commands.
I got the following response.

(picrust1) qiime@qiime-VirtualBox:~/Desktop$ which biom
/home/qiime/miniconda3/envs/picrust1/bin/biom
(picrust1) qiime@qiime-VirtualBox:~/Desktop$ biom --version
Traceback (most recent call last):
  File "/home/qiime/miniconda3/envs/picrust1/bin/biom", line 7, in <module>
    from biom.cli import cli
ImportError: No module named cli

Regards,

Chika

**Comment by chikalll** [comment]
Hi gavin

I retried to running commands.
I got the following response.

(picrust1) qiime@qiime-VirtualBox:/Desktop$ which biom
/home/qiime/miniconda3/envs/picrust1/bin/biom
(picrust1) qiime@qiime-VirtualBox:/Desktop$ biom --version
Traceback (most recent call last):
File "/home/qiime/miniconda3/envs/picrust1/bin/biom", line 7, in 
from biom.cli import cli
ImportError: No module named cli

Regards,

Chika

**Comment by gavinmdouglas** [comment]
Hi again,

It seems like something is wrong with your conda installation and/or python configuration. Have you previously added PYTHONPATH definitions to your bashrc configuration file? If so that could be related to this issue if a different python library is always being used.

Sorry I can't be of more help - I would recommend troubleshooting this problem just by installing biom (the package is called `biom-format` and is on the `bioconda` channel) in a new conda environment and trying to get that to work since I believe this is a more general conda/python issue.
